name = "Create & Co"
author = "Brizzy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e04a6c1db0eb6bec8e5fc67c8b638500035abe85227e650222d727b4a903180"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
