name = "Create & Co"
author = "Brizzy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27fb900166ebf35ce7454fbcf7b3029568a3737765c20d61909d5fc9deef5468"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
