name = "Create & Co"
author = "Brizzy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dde9460bdcc933aad789a90c6d691b12fd3a55cac75c17e74e287b36d3898022"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
